use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html

server:
  secret_key: "ultrasecretkey"  # 会被Dockerfile中的sed命令替换
  limiter: false
  image_proxy: false
  port: 8080
  bind_address: "0.0.0.0"
